services:
  mysql:
    image: mysql:8.0.30
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ../notes-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql
  backend:
    build:
      context: ../notes-backend
    container_name: backend-app
    networks:
      - backend
      - mysql
    depends_on:
      - mysql
    restart: always
  frontend:
    build:
      context: ../notes-frontend
    container_name: frontend-app
    ports:
    - 80:8081
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    restart: always
networks:
  mysql:
    driver: bridge
  backend:
    driver: bridge
  frontend:
    driver: bridge
volumes:
  mysql-data:
    driver: local